# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` 

In [14]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [15]:
pip show numpy

Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: c:\Users\majid\anaconda3\Lib\site-packages
Requires: 
Required-by: astropy, bokeh, Bottleneck, contourpy, cvzone, daal4py, datasets, datashader, datashape, gensim, h5py, holoviews, hvplot, imagecodecs, imageio, imbalanced-learn, keras, matplotlib, mkl-fft, mkl-random, ml-dtypes, numba, numexpr, opencv-python, opt-einsum, pandas, patsy, pyarrow, pyerfa, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, statsmodels, tables, tensorboard, tensorflow-intel, tifffile, torchvision, transformers, xarray
Note: you may need to restart the kernel to use updated packages.


#### 3. Create a null vector of size 10

In [16]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array 

In [17]:
x = np.array([100, 20, 34,50])
print(x)
print("Data type of array elements:", x.dtype)
 
print("Memory size of a NumPy array:",
      x.nbytes)

[100  20  34  50]
Data type of array elements: int32
Memory size of a NumPy array: 16


#### 5. How to get the documentation of the numpy add function from the command line?

In [18]:
print("Numpy documentation function")
np.__doc__

Numpy documentation function


'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [19]:
x= np.zeros(10)
x[4] = 1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49

In [20]:
x = np.arange(10,49,1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last)

In [21]:

import numpy as np
 
# initialising numpy array
ini_array = np.array([1,3,5,6,8,3,8])
 
# using shortcut method to reverse
res = np.flip(ini_array)
 
# printing result
print("final array", res)


final array [8 3 8 6 5 3 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
x = np.arange(2, 11).reshape(3, 3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [23]:
x = np.array([1, 2, 0, 0, 4, 0])
y = np.nonzero(x)[0]
print(y)

[0 1 4]


#### 11. Create a 3x3 identity matrix

In [24]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [25]:
x = np.random.random([3,3,3])
print(x)

[[[0.02756721 0.61164587 0.72424953]
  [0.24946933 0.54097236 0.35597479]
  [0.55204531 0.99394443 0.30181078]]

 [[0.56816194 0.8559177  0.85917172]
  [0.39639355 0.19062595 0.42892491]
  [0.83039794 0.01179491 0.88052109]]

 [[0.43078777 0.83592701 0.73759747]
  [0.16712099 0.3603176  0.40803756]
  [0.06212095 0.77354152 0.78542682]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
x = np.random.random([10,10])
minim = x.min()
maxim = x.max()
print("minimum value")
print(minim)
print("maximum value")
print(maxim)


minimum value
0.0007568051753537031
maximum value
0.9992327014465292


#### 14. Create a random vector of size 30 and find the mean value

In [27]:
x = np.random.random(30)
mean_value =x.mean()
print(mean_value)

0.4371643453512039


#### 15. Create a 2d array with 1 on the border and 0 inside

In [28]:
x = np.zeros((5, 5))


x[0, :] = 1 
x[-1, :] = 1  
x[:, 0] = 1    
x[:, -1] = 1   

print(x)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

#### 16. How to add a border (filled with 0's) around an existing array?

In [29]:
x = np.array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                           [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
x[0, :] = 0
x[-1, :] = 0
x[:, 0] = 0    
x[:, -1] = 0

print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
print(0 * np.nan)          
print(np.nan == np.nan)    
print(np.inf > np.nan)      
print(np.nan - np.nan)      
print(np.nan in set([np.nan]))  
print(0.3 == 3 * 0.1)       


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [31]:
x= np.zeros((5,5))
np.fill_diagonal(x[1:],[1,2,3,4])

print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
x =np.zeros((8,8))
x[2::1, ::2] = 1  # Fill even rows and even columns with 1
x[1::2, 1::2] = 1  # Fill odd rows and odd columns with 1 
print(x)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [33]:
import numpy as np

tile = np.array([[0, 1], [1, 0]])

checkerboard = np.tile(tile, (3, 3))

print(checkerboard)


[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [34]:
import numpy as np
matrix = np.random.random((5, 5))
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.04433107 0.01278542 0.65961324 0.99383837 0.16764146]
 [0.17232656 0.21866716 0.0384375  0.27856502 0.55152524]
 [0.1868553  0.80380248 0.98738073 0.8961117  0.23891211]
 [0.79293949 0.50889195 0.96223331 0.85016912 0.80635764]
 [0.15860613 0.18358963 0.43861911 0.89818626 0.55383379]]

Normalized Matrix:
[[0.03215489 0.         0.65931999 1.         0.15784677]
 [0.16262235 0.20985793 0.0261475  0.2709126  0.54914448]
 [0.17743169 0.80629395 0.99341764 0.90038594 0.23049387]
 [0.79522116 0.50568782 0.96778455 0.85355607 0.80889846]
 [0.14863695 0.17410295 0.43405781 0.90250056 0.55149762]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [35]:
import numpy as np

# Define the custom dtype for RGBA colors
rgba_dtype = np.dtype([
    ('r', np.uint8),  # Red channel
    ('g', np.uint8),  # Green channel
    ('b', np.uint8),  # Blue channel
    ('a', np.uint8)   # Alpha channel
])

# Create an array of colors using the custom dtype
colors = np.array([
    (255, 0, 0, 255),   # Red
    (0, 255, 0, 255),   # Green
    (0, 0, 255, 255),   # Blue
    (255, 255, 0, 255), # Yellow
    (255, 255, 255, 255) # White
], dtype=rgba_dtype)

# Print the array
print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255) (255, 255, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)


In [36]:
x = np.random.randint(1,4, size=(5,3))
y = np.random.randint(2,4,size=(3,2))
z = np.dot(x,y)
print("Product of array: ")
print(z)

Product of array: 
[[12 15]
 [10 11]
 [16 19]
 [12 14]
 [10 11]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [37]:
a = np.arange(8)
a[3:8] = np.negative(a[3:8])
print(a)

[ 0  1  2 -3 -4 -5 -6 -7]


#### 26. What is the output of the following script?
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [38]:
print(sum(range(5),-1)) #it give 9 result
from numpy import *
print(sum(range(5),-1)) # it give 10 result in numpy -1 will represent axis

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [39]:
"""All the given expressions (Z ** Z, 2 << Z >> 2, Z < -Z, 1j * Z, Z / 1 / 1, Z < Z < Z) are legal in Python for an integer vector Z"""

'All the given expressions (Z ** Z, 2 << Z >> 2, Z < -Z, 1j * Z, Z / 1 / 1, Z < Z < Z) are legal in Python for an integer vector Z'

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:

#RuntimeWarning: invalid value encountered in divide
#RuntimeWarning: divide by zero encountered in floor_divide
#RuntimeWarning: invalid value encountered in cast


#### 29. How to round away from zero a float array ?

In [41]:
array = np.array([1.7, -4.5, 8.9, -6, 8])
rounded_array = np.ceil(np.abs(array)) * np.sign(array)
print(rounded_array)

[ 2. -5.  9. -6.  8.]


#### 30. How to find common values between two arrays?

In [42]:
import numpy as np

array1 = np.array([1, 6, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)
print(common_values)

[4 5 6]


#### 31. How to ignore all numpy warnings (not recommended)?

In [43]:
# np.seterr(all='ignore') #i'm not running it because it not recommended

#### 32. Is the following expressions true?
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\majid\AppData\Local\Temp\ipykernel_6100\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [45]:
# Get today's date
today = np.datetime64('today')

# Get yesterday's date
yesterday = today - np.timedelta64(1)

# Get tomorrow's date
tomorrow = today + np.timedelta64(1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-07-05
Today: 2024-07-06
Tomorrow: 2024-07-07


#### 34. How to get all the dates corresponding to the month of July 2016?

In [46]:
# Get today's date
start = np.datetime64('2016-07-01')
end= np.datetime64('2016-07-30')
month =np.arange(start,end+np.timedelta64(1,))
print(month)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [47]:
import numpy as np

# Example arrays A and B
A = np.array([1, 2, 3], dtype=np.float64)  # Specify dtype=float64 for A
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
np.add(A, B, out=A)       # A = A + B
np.negative(A, out=A)     # A = -A
np.divide(A, 2, out=A)    # A = -A / 2
np.multiply(A, B, out=A)  # A = (A + B) * (-A / 2)

# Result is now stored in array A
print("Result:", A)


Result: [-10.  -17.5 -27. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [48]:
# Method 1: Using np.floor
random_array = np.random.rand(5) * 10  
integer_part_floor = np.floor(random_array)
print("Integer part (floor method):", integer_part_floor)

# Method 2: Using astype(int)
integer_part_astype = random_array.astype(int)
print("Integer part (astype method):", integer_part_astype)

# Method 3: Using np.trunc
integer_part_trunc = np.trunc(random_array)
print("Integer part (trunc method):", integer_part_trunc)

# Method 4: Using list comprehension with int conversion
integer_part_listcomp = [int(x) for x in random_array]
print("Integer part (list comprehension method):", integer_part_listcomp)


Integer part (floor method): [4. 0. 3. 3. 0.]
Integer part (astype method): [4 0 3 3 0]
Integer part (trunc method): [4. 0. 3. 3. 0.]
Integer part (list comprehension method): [4, 0, 3, 3, 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [49]:
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.arange(5).reshape(5, 1) + np.zeros((5, 5), dtype=int)

print(matrix)


[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array

In [50]:
import numpy as np

# Define a generator function that yields 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Use NumPy's fromiter to build an array from the generator
array = np.fromiter(generate_integers(), dtype=int, count=10)

print("Generated array:", array)


Generated array: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [51]:
x = np.linspace(0.01, 0.99, 10)
print(x)

[0.01       0.11888889 0.22777778 0.33666667 0.44555556 0.55444444
 0.66333333 0.77222222 0.88111111 0.99      ]


#### 40. Create a random vector of size 10 and sort it

In [52]:
x = random.rand(10)
y = np.sort(x)
print(y)

[0.05159717 0.07183011 0.09579812 0.26744635 0.27367363 0.29062273
 0.48848066 0.70976934 0.72096863 0.93096447]


#### 41. How to sum a small array faster than np.sum?

In [53]:

arr = np.array([1, 2, 3, 4, 5,6])
sum_result = np.add.reduce(arr)
print("Sum using np.add.reduce:", sum_result)

Sum using np.add.reduce: 21


#### 42. Consider two random array A and B, check if they are equal

In [54]:
x = np.random.rand(5)
y = np.random.rand(5)
if np.array_equal(x, y):
    print("Arrays are equal")
else:
    print("Arrays are not equal")



Arrays are not equal


#### 43. Make an array immutable (read-only) 

In [55]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Make the array immutable
arr.flags.writeable= False

# Try to modify the array
arr[0] = 10  # This will raise a ValueError

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

#### 45. Create random vector of size 10 and replace the maximum value by 0

In [56]:
import numpy as np

vector = np.random.rand(10)
print(vector)

max_index = np.argmax(vector)

vector[max_index] = 0

print("Original vector:", vector)


[0.93215063 0.14277829 0.71212338 0.32838262 0.07901333 0.9673708
 0.03124847 0.17049554 0.59018649 0.23857141]
Original vector: [0.93215063 0.14277829 0.71212338 0.32838262 0.07901333 0.
 0.03124847 0.17049554 0.59018649 0.23857141]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type

In [57]:
print("bool:", False, True)
print("int8:", np.iinfo(np.int8).min, np.iinfo(np.int8).max)
print("int16:", np.iinfo(np.int16).min, np.iinfo(np.int16).max)
print("int32:", np.iinfo(np.int32).min, np.iinfo(np.int32).max)
print("int64:", np.iinfo(np.int64).min, np.iinfo(np.int64).max)
print("uint8:", np.iinfo(np.uint8).min, np.iinfo(np.uint8).max)
print("uint16:", np.iinfo(np.uint16).min, np.iinfo(np.uint16).max)
print("uint32:", np.iinfo(np.uint32).min, np.iinfo(np.uint32).max)
print("uint64:", np.iinfo(np.uint64).min, np.iinfo(np.uint64).max)
print("float16:", np.finfo(np.float16).min, np.finfo(np.float16).max)
print("float32:", np.finfo(np.float32).min, np.finfo(np.float32).max)
print("float64:", np.finfo(np.float64).min, np.finfo(np.float64).max)
print("complex64:", np.finfo(np.complex64).min, np.finfo(np.complex64).max)
print("complex128:", np.finfo(np.complex128).min, np.finfo(np.complex128).max)

bool: False True
int8: -128 127
int16: -32768 32767
int32: -2147483648 2147483647
int64: -9223372036854775808 9223372036854775807
uint8: 0 255
uint16: 0 65535
uint32: 0 4294967295
uint64: 0 18446744073709551615
float16: -65500.0 65500.0
float32: -3.4028235e+38 3.4028235e+38
float64: -1.7976931348623157e+308 1.7976931348623157e+308
complex64: -3.4028235e+38 3.4028235e+38
complex128: -1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? 

In [58]:
arr = np.array([1, 2, 3, 4, 5])

for value in arr:
    print(value)


1
2
3
4
5


#### 50. How to find the closest value (to a given scalar) in a vector?

In [59]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
scalar = 3.7

index = np.argmin(np.abs(vector - scalar))
closest_value = vector[index]

print(closest_value)

4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [60]:
import numpy as np

dtype = [('position', [('x', float), ('y', float)]),
         ('color', [('r', int), ('g', int), ('b', int)])]


positions_colors = np.array([
    ((10.0, 20.0), (255, 0, 0)),
    ((15.5, 25.0), (0, 255, 0)),
    ((20.0, 30.5), (0, 0, 255))
], dtype=dtype)


print("Position of first element:", positions_colors['position'][0])
print("Color of first element:", positions_colors['color'][0])


Position of first element: (10., 20.)
Color of first element: (255, 0, 0)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [61]:
import numpy as np
coordinates = np.random.rand(100, 2)
distances = np.linalg.norm(coordinates[:, np.newaxis] - coordinates, axis=-1)
print("Pairwise distances:")
print(distances[:5, :5]) 


Pairwise distances:
[[0.         0.49919943 0.59414462 0.63910735 0.65698458]
 [0.49919943 0.         0.65135961 0.34877984 0.25412701]
 [0.59414462 0.65135961 0.         0.42076947 0.90539167]
 [0.63910735 0.34877984 0.42076947 0.         0.57741025]
 [0.65698458 0.25412701 0.90539167 0.57741025 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [62]:
import numpy as np

# Create a float32 array
float_array = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float32)
print(float_array)

float_array = float_array.astype(np.int32)

print("Float array (int32):", float_array)


[1.1 2.2 3.3 4.4]
Float array (int32): [1 2 3 4]


#### 54. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [63]:
# Define the input data
input_data = """1, 2, 3, 4, 5
6,  ,  , 7,
 ,  , 9, 10, 11"""

data = np.genfromtxt(input_data.splitlines(), delimiter=',', dtype=float)
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7. nan]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays?

In [64]:
#ndindex is used in place of enumerate
arr = np.array([[1, 2, 3], [4, 5, 6]])

for index in np.ndindex(arr.shape):
    print(index, arr[index])


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### 56. Generate a generic 2D Gaussian-like array

#### 57. How to randomly place p elements in a 2D array?

In [65]:
import numpy as np

rows = 3
cols = 5
p = 5


arr = np.random.randint(0, 2, size=(rows, cols))


positions = np.random.choice(rows * cols, p)


arr.flat[positions] = p

print("Randomly placed array:")
print(arr)


Randomly placed array:
[[1 5 5 1 1]
 [1 1 5 0 0]
 [5 0 0 5 1]]


#### 58. Subtract the mean of each row of a matrix

In [66]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_means = X.mean(axis=1, keepdims= True) 
Y = X - row_means
print(Y)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column?

In [67]:
arr = np.array([[4, 6, 2], [5, 1, 3], [7, 9, 8]])
n = 2
sorted_indices = np.argsort(-arr[:,n])
sorted_arr = arr[sorted_indices]

print(sorted_arr)

[[7 9 8]
 [5 1 3]
 [4 6 2]]


#### 60. How to tell if a given 2D array has null columns?

In [68]:
import numpy as np

# Example 2D array
array = np.array([[0, 0, 3],
                  [0, 0, 6],
                  [0, 0, 9]])

# Identify null (all-zero) columns
null_columns = np.where(~array.any(axis=0))[0]

print("Array:")
print(array)

if null_columns.size > 0:
    print("\nThe array has null (all-zero) columns at indices:", null_columns)
else:
    print("\nThe array does not have any null (all-zero) columns.")


Array:
[[0 0 3]
 [0 0 6]
 [0 0 9]]

The array has null (all-zero) columns at indices: [0 1]


#### 61. Find the nearest value from a given value in an array

In [69]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5,9])
value = 8

index = np.argmin(np.abs(vector - value))
closest_value = vector[index]

print(closest_value)

9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [70]:
import numpy as np

A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)

it = np.nditer([A, B,None])

for x, y, z in it:
    z[...] = x + y

print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute

In [71]:
class MyArray:
  def __init__(self, data, name):
    self.data = data  
    self.name = name  


my_array = MyArray([1, 2, 3], "Sample Array")

print(f"Array name: {my_array.name}")
print(f"Array data: {my_array.data}")

Array name: Sample Array
Array data: [1, 2, 3]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [72]:
vector = np.array([1, 2, 3, 4, 5])
index_vector = np.array([1, 2, 3, 4])

result_vector = vector.copy()

unique_indices = np.unique(index_vector)

result_vector[unique_indices] += 1
print("Original Vector:")
print(vector)

print("\nIndex Vector:")
print(index_vector)

print("\nResult Vector after adding 1 to unique indices:")
print(result_vector)


Original Vector:
[1 2 3 4 5]

Index Vector:
[1 2 3 4]

Result Vector after adding 1 to unique indices:
[1 3 4 5 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [73]:


X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 1, 3])

F = np.bincount(I, weights=X)
F = F.astype(np.int32)
print("Result:")
print(F)

Result:
[1 6 3 5]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [74]:


w, h = 640, 480


image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.ubyte)

unique_colors = set(map(tuple, image.reshape(-1, 3)))

num_unique_colors = len(unique_colors)

print(f"Number of unique colors: {num_unique_colors}")



Number of unique colors: 304433


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [75]:

arr = np.random.randint(0, 4, size=(3, 4, 5, 6))


sum_last_two_axes = np.sum(arr, axis=(-2, -1))

print("Original array shape:", arr.shape)
print("Sum over the last two axes shape:", sum_last_two_axes.shape)
print("Sum over the last two axes:")
print(sum_last_two_axes)


Original array shape: (3, 4, 5, 6)
Sum over the last two axes shape: (3, 4)
Sum over the last two axes:
[[54 46 48 51]
 [46 47 54 37]
 [49 52 47 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

In [76]:
D = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]) 
S = np.array([0, 0, 1, 1, 2, 2, 3, 3, 3])          


subset_means = []
for idx in np.unique(S):
    subset_means.append(np.mean(D[S == idx]))

print("Original vector D:", D)
print("Subset indices vector S:", S)
print("Subset means:", subset_means)


Original vector D: [10 20 30 40 50 60 70 80 90]
Subset indices vector S: [0 0 1 1 2 2 3 3 3]
Subset means: [15.0, 35.0, 55.0, 80.0]


#### 69. How to get the diagonal of a dot product?

In [77]:
import numpy as np
A = np.arange(1, 10).reshape(3, 3)

B = np.arange(1, 10).reshape(3, 3)


dot_product = np.dot(A, B)


diagonal_elements = np.diag(dot_product)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Dot product of A and B:\n", dot_product)
print("Diagonal elements of the dot product:\n", diagonal_elements)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dot product of A and B:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Diagonal elements of the dot product:
 [ 30  81 150]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [78]:
# Original vector
original_vector = [1, 2, 3, 4, 5]

# Build new vector with interleaved zeros
new_vector = []
for num in original_vector:
    new_vector.extend([num, 0, 0, 0])

# Remove the last set of zeros if it exists
for i in new_vector:
    if new_vector[-1] == 0:
        new_vector.pop()

print("Original vector:", original_vector)
print("New vector with zeros interleaved:", new_vector)


Original vector: [1, 2, 3, 4, 5]
New vector with zeros interleaved: [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [79]:
import numpy as np

# Create arrays
array_3d = np.random.randint(1, 10, size=(5, 5, 3))  # Dimension (5, 5, 3)
array_2d = np.random.randint(1, 10, size=(5, 5))    # Dimension (5, 5)

# Multiply using tile
result = array_3d * array_2d[:,:,None]

print("\nResult after multiplication (dimensions (5, 5, 3)):\n", result)



Result after multiplication (dimensions (5, 5, 3)):
 [[[54 63 54]
  [28 24 20]
  [10 15 45]
  [10 25 45]
  [20 16 36]]

 [[16 14 16]
  [ 5 10 10]
  [ 8 12 18]
  [54 18 54]
  [ 9  4  1]]

 [[ 5 35 20]
  [12 18 24]
  [18 21  3]
  [36 12 48]
  [ 6 10  4]]

 [[10  2  2]
  [42 42 18]
  [63 28 21]
  [10  8 12]
  [20 25 15]]

 [[ 6 21  6]
  [ 2 18  6]
  [32 56 64]
  [56  8 32]
  [ 8 32 16]]]


#### 72. How to swap two rows of an array?

In [80]:
import numpy as np

# Create a sample 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swap rows (for example, swap row 0 with row 1)
arr[[0, 1]] = arr[[1, 0]]

print("Array after swapping rows 0 and 1:")
print(arr)


Array after swapping rows 0 and 1:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [81]:

triangle_vertices = [
    [(0, 0), (1, 0), (0, 1)],    # Triangle 1
    [(1, 0), (1, 1), (0, 1)],    # Triangle 2
    [(1, 1), (2, 1), (1, 2)],    # Triangle 3
    [(1, 1), (1, 2), (0, 1)],    # Triangle 4
    [(1, 0), (2, 0), (1, 1)],    # Triangle 5
    [(2, 0), (2, 1), (1, 1)],    # Triangle 6
    [(2, 1), (2, 2), (1, 1)],    # Triangle 7
    [(1, 1), (2, 2), (1, 2)],    # Triangle 8
    [(0, 0), (1, 0), (1, 1)],    # Triangle 9
    [(1, 1), (1, 0), (0, 1)]     # Triangle 10
]


unique_segments = set()

for vertices in triangle_vertices:
 
    segments = {(vertices[i], vertices[(i + 1) % 3]) for i in range(3)}
 
    unique_segments.update(segments)


print("Unique line segments composing all triangles:")
for segment in unique_segments:
    print(segment)


Unique line segments composing all triangles:
((1, 0), (0, 1))
((1, 1), (0, 1))
((0, 1), (1, 0))
((0, 0), (1, 0))
((2, 0), (2, 1))
((1, 2), (0, 1))
((2, 0), (1, 1))
((0, 1), (1, 1))
((1, 1), (1, 0))
((2, 1), (1, 1))
((2, 2), (1, 1))
((1, 1), (2, 1))
((1, 0), (1, 1))
((1, 0), (2, 0))
((0, 1), (0, 0))
((1, 1), (2, 0))
((2, 1), (2, 2))
((1, 1), (2, 2))
((2, 1), (1, 2))
((1, 2), (1, 1))
((2, 2), (1, 2))
((1, 1), (0, 0))
((1, 1), (1, 2))


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [82]:
import numpy as np


C = np.array([0, 1, 2, 0, 1, 2, 3, 0, 1, 4])

A = []


for index, count in enumerate(C):
    A.extend([index] * count)

# Convert to numpy array
A = np.array(A)


print("Array A:", A)
print("Bincount of A:", np.bincount(A))
print("Original array C:", C)


Array A: [1 2 2 4 5 5 6 6 6 8 9 9 9 9]
Bincount of A: [0 1 2 0 1 2 3 0 1 4]
Original array C: [0 1 2 0 1 2 3 0 1 4]


#### 75. How to compute averages using a sliding window over an array?

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [83]:
# Example:
Z = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Build the two-dimensional array
result = []
for i in range(len(Z) - 2):
    result.append(Z[i:i+3])

# Print the result
for row in result:
    print(row)


[1, 2, 3]
[2, 3, 4]
[3, 4, 5]
[4, 5, 6]
[5, 6, 7]
[6, 7, 8]
[7, 8, 9]


#### 77. How to negate a boolean, or to change the sign of a float inplace?

In [84]:

bool_value = True


negated_bool = not bool_value

print(negated_bool) 


False


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [85]:
import numpy as np

Z = np.arange(1, 15, dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z, shape=(11, 4), strides=(4, 4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [86]:
import numpy as np

# Define your matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the rank of the matrix A
rank_A = np.linalg.matrix_rank(A)

print("Rank of matrix A:", rank_A)


Rank of matrix A: 2


#### 83. How to find the most frequent value in an array?

In [87]:
Z =np.array([3,5,6,7,8,8,6,4,3,8])
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [93]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

# Create a random 10x10 matrix
Z = np.random.randint(0, 5, (10, 10))

# Define block size and calculate dimensions
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)

# Create the view with overlapping 3x3 blocks
C = as_strided(Z, shape=(i, j, n, n), strides=Z.strides * 2)

print(C)


[[[[1 4 0]
   [2 4 1]
   [3 3 3]]

  [[4 0 2]
   [4 1 1]
   [3 3 1]]

  [[0 2 1]
   [1 1 0]
   [3 1 1]]

  [[2 1 2]
   [1 0 4]
   [1 1 2]]

  [[1 2 4]
   [0 4 1]
   [1 2 4]]

  [[2 4 3]
   [4 1 1]
   [2 4 0]]

  [[4 3 2]
   [1 1 4]
   [4 0 2]]

  [[3 2 1]
   [1 4 0]
   [0 2 2]]]


 [[[2 4 1]
   [3 3 3]
   [1 1 2]]

  [[4 1 1]
   [3 3 1]
   [1 2 4]]

  [[1 1 0]
   [3 1 1]
   [2 4 1]]

  [[1 0 4]
   [1 1 2]
   [4 1 1]]

  [[0 4 1]
   [1 2 4]
   [1 1 3]]

  [[4 1 1]
   [2 4 0]
   [1 3 3]]

  [[1 1 4]
   [4 0 2]
   [3 3 0]]

  [[1 4 0]
   [0 2 2]
   [3 0 0]]]


 [[[3 3 3]
   [1 1 2]
   [4 3 3]]

  [[3 3 1]
   [1 2 4]
   [3 3 0]]

  [[3 1 1]
   [2 4 1]
   [3 0 4]]

  [[1 1 2]
   [4 1 1]
   [0 4 1]]

  [[1 2 4]
   [1 1 3]
   [4 1 1]]

  [[2 4 0]
   [1 3 3]
   [1 1 0]]

  [[4 0 2]
   [3 3 0]
   [1 0 4]]

  [[0 2 2]
   [3 0 0]
   [0 4 1]]]


 [[[1 1 2]
   [4 3 3]
   [4 0 3]]

  [[1 2 4]
   [3 3 0]
   [0 3 4]]

  [[2 4 1]
   [3 0 4]
   [3 4 2]]

  [[4 1 1]
   [0 4 1]
   [4 2 1]]

  [[1 1 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [89]:

p = 3  
n = 3  
matrices = np.ones((p, n, n)) 
vectors = np.ones((p, n, 1))   
result = np.sum(np.matmul(matrices, vectors), axis=0, dtype=int32)
print("Result shape:", result.shape)
print(result)


Result shape: (3, 1)
[[9]
 [9]
 [9]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

In [94]:
array = np.arange(16*16).reshape(16, 16)
block_size = 4
reshaped = array.reshape(16//block_size, block_size, 16//block_size, block_size)

block_sums = reshaped.sum(axis=(1, 3))
print("Original array:")
print(array)
print("\nBlock sums:")
print(block_sums)


Original array:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

In [95]:
values = [10, 5, 8, 2, 9, 3]
n = 4

sorted_values = sorted(values, reverse=True)

counter = 1
for value in sorted_values:
    if counter == n:
        print(value)
        break
    counter += 1

5


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

In [96]:
import itertools
import numpy as np

# Define an arbitrary number of vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5,4])

# Use itertools.product to compute the Cartesian product
cartesian_product = list(itertools.product(vector1, vector2))

# Convert the list of tuples to a numpy array
cartesian_product_array = np.array(cartesian_product)

print("Cartesian product:")
print(cartesian_product_array)


Cartesian product:
[[1 4]
 [1 5]
 [1 4]
 [2 4]
 [2 5]
 [2 4]
 [3 4]
 [3 5]
 [3 4]]


#### 91. How to create a record array from a regular array?

In [97]:
import numpy as np

# Suppose you have three arrays: a1, a2, and a3
a1 = np.array([1, 2, 3])
a2 = np.array([10.5, 20.5, 30.5])
a3 = np.array([100, 200, 300])

# Create a structured array from the arrays
result = np.core.records.fromarrays([a1, a2, a3], names='a,b,c')

print("Structured Array:")
print(result)


Structured Array:
[(1, 10.5, 100) (2, 20.5, 200) (3, 30.5, 300)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [98]:
print("Method 1")
Z = np.random.randint(6,10,size=(5,5)) 
Z_cubed_explicit = Z * Z * Z
print(Z_cubed_explicit)
print("Method 2")
Z_cubed = np.power(Z, 3)
print(Z_cubed)
print("Method 3")
Z_cubed_alt = Z ** 3
print(Z_cubed_alt)


Method 1
[[512 216 343 729 512]
 [216 729 729 729 729]
 [512 729 216 343 729]
 [216 512 729 343 729]
 [216 216 343 216 216]]
Method 2
[[512 216 343 729 512]
 [216 729 729 729 729]
 [512 729 216 343 729]
 [216 512 729 343 729]
 [216 216 343 216 216]]
Method 3
[[512 216 343 729 512]
 [216 729 729 729 729]
 [512 729 216 343 729]
 [216 512 729 343 729]
 [216 216 343 216 216]]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [99]:


A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [100]:
import numpy as np


nums = np.random.randint(0, 4, (10, 3))


unequal_rows = []

for row in nums:

    if row[0] != row[1] or row[1] != row[2]:
        unequal_rows.append(row)


print("Original matrix:")
print(nums)

print("\nRows with unequal consecutive values:")
for row in unequal_rows:
    print(row)


Original matrix:
[[2 1 1]
 [1 3 3]
 [1 1 1]
 [1 2 3]
 [3 2 3]
 [1 3 3]
 [3 2 3]
 [2 1 1]
 [3 2 1]
 [0 3 1]]

Rows with unequal consecutive values:
[2 1 1]
[1 3 3]
[1 2 3]
[3 2 3]
[1 3 3]
[3 2 3]
[2 1 1]
[3 2 1]
[0 3 1]


#### 95. Convert a vector of ints into a matrix binary representation

In [101]:
import numpy as np


vector = np.array([1, 2, 0, 3])
num_classes = np.max(vector) + 1


binary_matrix = np.eye(num_classes)[vector]

print("Vector:")
print(vector)
print("\nBinary Matrix Representation:")
print(binary_matrix.astype(int))


Vector:
[1 2 0 3]

Binary Matrix Representation:
[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows?

In [102]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [1, 2, 3],
                   [7, 8, 9]])


unique_rows = np.unique(matrix, axis=0)

print("Original Matrix:")
print(matrix)
print("\nUnique Rows:")
print(unique_rows)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]]

Unique Rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [103]:
import numpy as np


A = np.array([1, 2, 3])
B = np.array([4, 5, 6])


inner_product = np.einsum('i,i->', A, B)


outer_product = np.einsum('i,j->ij', A, B)

total_sum = np.einsum('i->', A)


elementwise_product = np.einsum('i,i->i', A, B)


print("Inner Product:", inner_product)
print("Outer Product:")
print(outer_product)
print("Sum of elements:", total_sum)
print("Element-wise Product:")
print(elementwise_product)


Inner Product: 32
Outer Product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of elements: 6
Element-wise Product:
[ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [104]:
import numpy as np


X = np.array([[1, 2, 3],
              [0, 5, 5],
              [2, 3, 4],
              [3, 1, 2],
              [4, 0, 3]])


n = 6


selected_rows = X[(X.sum(axis=1) == n) & np.all(X.astype(int) == X, axis=1)]


print("Rows from X that are draws from a multinomial distribution with sum", n, ":")
for row in selected_rows:
    print(row)


Rows from X that are draws from a multinomial distribution with sum 6 :
[1 2 3]
[3 1 2]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [105]:
import numpy as np

X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

N = 1000

bootstrap_means = np.random.choice(X, size=(N, len(X)), replace=True).mean(axis=1)

confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])

print(f"Bootstrap 95% Confidence Interval for the Mean: {confidence_interval}")


Bootstrap 95% Confidence Interval for the Mean: [3.6 7.2]
